steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKER_HUB_CREDENTIALS']
    args:
      - '-c'
      - |
        echo "$DOCKER_HUB_CREDENTIALS" | docker login --username=evdev3 --password-stdin

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/evdev3/transcription-api:$COMMIT_SHA', '.', '-f', 'Dockerfile']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/evdev3/transcription-api:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run', 'deploy', 'transcription-api',
        '--image', 'docker.io/evdev3/transcription-api:$COMMIT_SHA',
        '--region', 'us-east1', '--platform', 'managed',
        '--allow-unauthenticated', '--quiet'
      ]

availableSecrets:
  secretManager:
    - versionName: projects/neuralnexus-467517/secrets/docker-hub-credentials/versions/latest
      env: DOCKER_HUB_CREDENTIALS

options:
  logging: CLOUD_LOGGING_ONLY
