services:
  transcription-api:
    container_name: transcription-api
    image: evdev3/transcription-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - .env