name: Build and Deploy to Docker Hub and GCP Cloud Run

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: evdev3/transcription-api
  SERVICE_NAME: transcription-api
  REGION: us-east1
  PROJECT_ID: neuralnexus-467517

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ env.IMAGE_NAME }}:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
            project_id: ${{ env.PROJECT_ID }}
          
      - name: Deploy to Cloud Run
        run: |
          export IMAGE_NAME=${{ env.IMAGE_NAME }}
          export SERVICE_NAME=${{ env.SERVICE_NAME }}
          export REGION=${{ env.REGION }}
              
          gcloud run deploy $SERVICE_NAME \
            --image=docker.io/$IMAGE_NAME:latest \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=POSTGRES_HOST=localhost,MONGO_DB=mongo_db,MONGO_HOST=localhost,REDIS_HOST=redis,REDIS_PORT=6379,WEBSOCKET_PORT=8765 \
            --memory=1Gi

            